services:
  - type: web
    name: radio-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
    healthCheckPath: /
    autoDeploy: true 